# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, Test and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./static-files

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...
      
    - name: Static Check
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
      
    - name: Test
      run: go test -v ./...
