name: Create Release and Upload Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'  # Specify the Go version you want to use

    - name: Build
      run: go build -v ./...
      working-directory: ./static-files
      
    - name: Get latest Git tag
      id: get-tag
      run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)      
      
    - name: Create a new release
      id: create-release
      uses: softprops/action-gh-release@v1
      with:
        files: static-files/static-files
        tag_name: ${{ steps.get-tag.outputs.tag }}
        title: Release ${{ steps.get-tag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
