name: Create Release and Upload Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        
    - name: Build
      run: go build -v ./...
      working-directory: ./static-files
      
    - name: Create a new release
      uses: softprops/action-gh-release@v1
      with:
        files: static-files/static-files
